# Use root/example as user/password credentials
version: '3.1'

services:

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached 
    command: sleep infinity
    
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080