version: '3'

services:

  devcontainer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached 
    command: sleep infinity
    
    # GPU acceleration?
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - mysql-data:/var/lib/mysql
  
  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  mysql-data: